FROM smbarge/excise:pcb01_server
WORKDIR /usr/src/app
ENV PORT 5000
ENV VITE_APISERVER=https://pcb01.parikshaworld.com
ENV DB_URI="mongodb+srv://smbarge:csswakad%408782@cluster-01.9ufne.mongodb.net/pcb-01-2023?retryWrites=true&w=majority"
ENV AWS_ACCESS_KEY_ID="AKIASBOROETZ2N5PRX4X"
ENV AWS_SECRET_ACCESS_KEY="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"
EXPOSE $PORT
CMD ["npm","run","start"]

